version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    on-failure: ABORT
    commands:
      - mvn clean install
  pre_build:
    on-failure: ABORT
    commands:
      - export VERSION=$(echo ${CODEBUILD_BUILD_NUMBER})
  build:
    on-failure: ABORT
    commands:
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_REPO
      - docker build -t springboot-cicd-api:$VERSION .
      - docker tag springboot-cicd-api:$VERSION $ECR_REPO:$VERSION
      - docker tag springboot-cicd-api:$VERSION $ECR_REPO:latest
  post_build:
    on-failure: ABORT
    commands:
      - docker push $ECR_REPO:$VERSION
      - docker push $ECR_REPO:latest
      - aws eks update-kubeconfig --name $EKS_CLUSTER
      - envsubst < api.yaml | kubectl apply -f -
